config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :sessions
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  paginates_per 24
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticated?
  helper_method :current_user

  def authenticate_user(user_id, password)
    begin
      user = User.find_by_login(user_id).authenticate(password)
      rescue NoMethodError
        flash[:notice] = "Login and password incorrect"
        redirect_to "/sessions/new"
    end
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      false
    end
  end

  def authenticated?
    unless current_user
      redirect_to "/sessions/new"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:category] && params[:category] != ""
      @category = params[:category]
      @products = Category.find_by_name(params[:category]).products
    end
    if params[:no_price]  && params[:no_price] != ""
      @no_price = true
      @products = @products.where(price: nil)
    end
    if params[:brand] && params[:brand] != ""
      @brand = params[:brand]
      @products = @products.where(brand: params[:brand])
    end
    if params[:done] && params[:done] != ""
      @done = true
      @products = @products.where(done: true)
    else
      @products = @products.where(done: false)
    end
    if params[:page_number]
      @products = @products.page(params[:page_number])
    else
      @products = @products.page(1)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        @product.categories.each do |category|
          @product.categories.delete(category)
        end
        if params[:product][:category_ids]
          params[:product][:category_ids].each do |id|
            @product.categories.push(Category.find(id))
          end
        end
        @product.update(done: true)
        format.js
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_ids)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticated?, only: [:new, :create, :destroy]
  def new

  end

  def create
    authenticate_user(params[:login], params[:password])
    redirect_to products_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/sessions/new"
  end
private
  def sessions_params
    params.permit(:login, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataEntryTools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
    <%= link_to "Log Out", session_path(1), :method => "delete" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div style="width: 50%; float: left;">
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :description %>
      <%= f.text_area :description %>
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
    <div style="width: 50%; float: left;">
      <% Category.all.each do |category| %>
        <%= check_box_tag "product[category_ids_#{category.id}][]", category.id, f.object.categories.include?(category) %>
        <%= label_tag "product[category_ids_#{category.id}][]", category.name, style: "display: inline-block;" %>
        <br>
      <% end %>
    </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div style="width: 50%; float: left;">
  <h1>Editing Product</h1>
  <h2><%= @product.name %></h2>
  <img src="<%= @product.thumbnail %>" alt="">
</div>
<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center;">Products</h1>

<div style="width: 25%; float: left; margin-bottom: 40px;">
  <h3>Brands</h3>
  <%= select_tag :brand, options_for_select([['All', nil], ["Homelegance", "Homelegance"], ["Furniture of America", "Furniture of America"]], selected: @brand), onchange: "window.location = '/products?#{params.permit!.except(:action, :controller, :brand).to_query}&brand=' + $(this).val();" %>
</div>
<div style="width: 25%; float: left;">
  <h3>Category</h3>
    <%= select_tag :category, options_for_select(Category.all.map {|e| e.name}.unshift(['All', nil]), selected: @category), onchange: "window.location = '/products?#{params.permit!.except(:action, :controller, :category).to_query}&category=' + $(this).val();" %>
</div>
<div style="width: 25%; float: left;">
  <h3>Prices</h3>
    <%= select_tag :brand, options_for_select([['All', nil], ["No Price", true]], selected: @no_price), onchange: "window.location = '/products?#{params.permit!.except(:action, :controller, :no_price).to_query}&no_price=' + $(this).val();" %>
</div>
<div style="width: 25%; float: left;">
  <h3>Done?</h3>
  <%= select_tag :not_done, options_for_select([['Not Done', nil], ["Done", true]], selected: @done), onchange: "window.location = '/products?#{params.permit!.except(:action, :controller, :done).to_query}&done=' + $(this).val();" %>
</div>

<div style="display: table; content: ''; clear: both;"></div>

<div style="float: left; text-align: center; width: 100%;">
  <% @products.page(1).total_pages.times do |time| %>
    <% if time + 1 == @products.current_page %>
      <p class="active" style="display: inline-block; margin: 0;"><%=(time + 1) %> |</p>
    <% else %>
      <p style="display: inline-block; margin: 0;"><%= link_to (time + 1), "/products?#{params.permit!.except(:action, :controller, :page_number).to_query}&page_number=#{time + 1}" %> |</p>
    <% end %>
  <% end %>
</div>

<div style="display: table; content: ''; clear: both;"></div>

<% @products.each do |product| %>
  <div style="width: 33%; float: left; padding: 15px; box-sizing: border-box;" id="product_<%= product.id %>">
    <h2><%= product.name %></h2>
    <%= link_to edit_product_path(product) do %>
      <img src="<%= product.thumbnail %>" style="max-width:100%; height: 500px;">
    <% end %>
    <%= form_for(product, remote: true) do |f|%>
    <div style="width: 50%; float: left;">
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :description %>
      <%= f.text_area :description %>
      <%= f.label :price %>
      <%= f.text_field :price %>
      <br>
      <br>
      <div id="product_submit_<%= product.id %>"></div>
      <%= f.submit "Submit" %>
    </div>
    <div style="width: 50%; float: left;">
      <% Category.all.each do |category| %>
        <%= check_box_tag "product[category_ids][]", category.id, f.object.categories.include?(category), id: "product_#{product.id}_category_ids_#{category.id}" %>
        <%= label_tag "product_#{product.id}_category_ids_#{category.id}", category.name, style: "display: inline-block;" %>
        <br>
      <% end %>
    </div>
    <% end %>
    <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>

<div style="float: left; width: 100%; text-align: center;">
  <% @products.page(1).total_pages.times do |time| %>
    <% if time + 1 == @products.page(1).current_page %>
      <p class="active" style="display: inline-block; margin: 0;"><%= link_to (time + 1), "/products?#{params.permit!.except(:action, :controller, :page_number).to_query}&page_number=#{time + 1}" %> |</p>
    <% else %>
      <p style="display: inline-block; margin: 0;"><%= link_to (time + 1), "/products?#{params.permit!.except(:action, :controller, :page_number).to_query}&page_number=#{time + 1}" %> |</p>
    <% end %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/update.js.erb
$(function() {
  $("#product_submit_<%= @product.id %>").append("Product updated");
  $("#product_<%= @product.id %>").remove();
})